### ISSUE TITLE
20211220リリース用TODO

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/vaccinecert-faq#26]
プログラム以外にやるべきこと

## TODO

- [x] Code for JapanからのAWSアカウント払い出し
- [x] AWS Amplifyへのデプロイ
  - [x] 公開まではBasic認証付けておくか？
- [x] 公開用のドメインとサブドメインを決める
- [x] DNSにAmplifyのendpointを登録
- [x] 本番サイトのBASIC認証外す

**Comment by jacoyutorius** [comment]
@euledge @ww2or3ww  アカウント発行されたらモブプロでAmplify関連の設定作業しませんか？

**Comment by ww2or3ww** [comment]
いいですね〜
19時以降であればいつでもOKですが、子供が寝たあとの21時以降がいいかなぁ。

**Comment by euledge** [comment]
やりたいやりたい!

**Comment by jacoyutorius** [comment]
@ww2or3ww @euledge  明日17日の23時とかでもいいですか・・・？

### TODO

- [ ] デプロイ用IAMロールを作成し、`amplify configure`
- [ ] amplify initして `add hosting`。Githubと接続してCI/CDできるようにする
- [ ] Basic認証をかける
- [ ] プルリクをマージして自動デプロイされるか確認する

所要時間1〜1.5hほど

**Comment by euledge** [comment]
OKです

**Comment by jacoyutorius** [comment]
やば、間違えました `16日(木) 23:00~` のつもりでした（日が変わってたの気づかず。。）
予定いかがでしょう？ @euledge @ww2or3ww

**Comment by euledge** [comment]
私も今晩のつもりでした(笑)

**Comment by jacoyutorius** [comment]
23時よりこちらでやりましょ〜
https://chime.aws/8711195292

**Comment by euledge** [comment]
## Top
![image](https://user-images.githubusercontent.com/1209580/146673181-c6fb5f16-2862-4ebf-af02-69f072cff60c.png)
## カテゴリ別
![image](https://user-images.githubusercontent.com/1209580/146673167-07cf6b74-46ca-4dde-ab8b-5ae8e643b108.png)
## About ページ
![image](https://user-images.githubusercontent.com/1209580/146673201-656898dd-f484-4f48-a06c-e59e84de2646.png)

**Comment by euledge** [comment]
皆さんお疲れさまでした！
また次のマイルストーン決めないとですね
